name: Build / Quality

on:
    push:
        branches:
            - main
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache modules
              uses: actions/cache@v1.1.2
              id: yarn-cache
              with:
                  node-version: '19.1.0'
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.2

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Prettier
              run: yarn prettier

            - name: Test
              run: yarn test --coverage --passWithNoTests --watchAll=false
              env:
                  CI: true

            - name: Generate build
              run: yarn build

            - name: Share artifact inside workflow
              uses: actions/upload-artifact@v1
              with:
                  name: devops
                  path: build
